### ISSUE TITLE
Remove border for first/latest slide item ?

### ISSUE THREAD

**Issue by ocvninfo** [sachinchoolur/lightslider#100]
I want to make my slider as below:
slide 1 | slide 2 | slide 3 | slide 4 | slide 5

if loop == true then i can remove border-left first item with active class. 
But it's not work with loop == false

**Comment by sachinchoolur** [comment]
Hi,
I am really sorry. i could not replay you on time.
I think you can add a class for the first children and remove border even if loop is false 
``` javascript
$('#lightSlider').children().first().addClass('no-border');
```
