### ISSUE TITLE
Incorrect "height" value when using "adaptiveHeight: true"

### ISSUE THREAD

**Issue by zoltalar** [sachinchoolur/lightslider#101]
Greetings,

I noticed an issue with the height of the container when "adaptiveHeight" is set to "true". When the container has padding and/or margin applied, then the slide is being clipped. When you run:

    $('#comment-slider').lightSlider({
        adaptiveHeight: true,
        item: 1,
        slideMargin: 0,
        loop: true,
        auto: true,
        pause: 5000
    });

On:

    <ul id="comment-slider">
        <li>Item 1</li>
        <li>Item 2</li>
    </ul>

Let's assume that you have margin-bottom and padding-top set to 20px for each "li" item, then the height of each slide would not be set properly. Please use "outerHeight()" function instead of "height()", as such:

    if (settings.adaptiveHeight === true && settings.vertical === false) {
        $el.css('height', $children.eq(scene).outerHeight(true));
    }

Thanks,
Z

**Comment by sachinchoolur** [comment]
Hi,
I have updated this.
Thanks :+1:
