### ISSUE TITLE
Pause on hover just with settings

### ISSUE THREAD

**Issue by aleixfabra** [sachinchoolur/lightslider#103]
Pause lightslider animation on hover with settings instead of calling `pause()` method.

`$('#autoplay').lightSlider({
    pauseOnHover: true
});`

**Comment by elboletaire** [comment]
:+1:

**Comment by sachinchoolur** [comment]
Hi,
I have added this feature in version 1.1.4.. Please check  the public methods example https://sachinchoolur.github.io/lightslider/examples.html

**Comment by aleixfabra** [comment]
:+1:
