### ISSUE TITLE
Follow the CSS coding standard

### ISSUE THREAD

**Issue by elboletaire** [sachinchoolur/lightslider#104]
You are using names for your classes that are not following none of the most used standards...

- http://primercss.io/guidelines/#examples
- http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml?showone=ID_and_Class_Name_Delimiters#ID_and_Class_Name_Delimiters
- https://make.wordpress.org/core/handbook/coding-standards/css/
- https://github.com/necolas/idiomatic-css#4-format

This is a bit annoying because I follow the basic standard of naming classes and ids with hypens and every time I need to style one of your plugins' classes I need to check the code to see how is it written.

If this is a pain for you, tell me, and I'll do a PR with these changes.

**Comment by aleixfabra** [comment]
:+1:

**Comment by sachinchoolur** [comment]
Hi,
I got some issues after merging this pull request. So i reverted back to the old copy.
I will  work on this issue after releasing lightGallery version 1.2.
Thank you very much for your support so far.

**Comment by elboletaire** [comment]
Hhhmmm.. what issues? :confused: I've that version working on a project without any problem.

**Comment by sachinchoolur** [comment]
When loop is true last slide was not working properly. I have copied files from your repo and checked.
It has same issue.
That might be a small issue but I did not attempt to debug because there ware lots of changes and it is difficult to crosscheck. I will do it once lightGallery is ready.

Thanks.
