### ISSUE TITLE
IE8 throws an error on window resize

### ISSUE THREAD

**Issue by creatorgr** [sachinchoolur/lightslider#105]
Hello and congrats for the great work! 

I found a small issue when testing the slider using IE8. If you try to resize the window after the page loads you'll find an issue in this line:

https://github.com/sachinchoolur/lightslider/blob/master/lightSlider/js/jquery.lightSlider.js#L1022

Are there any hacks to fix this issue?

**Comment by sachinchoolur** [comment]
Hi,
Could you please comment here what error message you are getting and your website url if it is available.

**Comment by creatorgr** [comment]
The problem has to do with the line e.preventDefault(); which is not supported by IE8 as I found.

**Comment by sachinchoolur** [comment]
Hi,
I have updated this 
``` javascript 
if (e.preventDefault) {
    e.preventDefault();
} else {
    e.returnValue = false;
}
```
Could you please test this on IE8 because I don't have IE 8. Normally i use developer toolbar to change the version.but sometime it does not work properly 

Thanks

**Comment by creatorgr** [comment]
Yes I think this is fixed. Thanks! but still I'm getting a weird "Member not found" error. Not sure what it is...
