### ISSUE TITLE
lightSlider with separate lightGallery

### ISSUE THREAD

**Issue by martyf** [sachinchoolur/lightslider#107]
It would be great if lightSlider could be used with a separate lightGallery to enable the lightGallery to be styled differently (i.e. different width, position, etc) to the lightSlider.

**Comment by sachinchoolur** [comment]
I am not sure what you mean exactly. If you want to style lightGallery separately you can use `addClass`  setting for adding custom class to lightGallery.
ex : 
``` javascript
$('#lightGallery').lightGallery({
    addClass : 'custome-class'    
});
```
`custome-class` will be added to the outer div of lightGallery
```html 
<div id="lg-outer" class="custome-class"></div>
```

**Comment by martyf** [comment]
Something like this:

![image](https://cloud.githubusercontent.com/assets/1491079/6912262/8da574d6-d7b9-11e4-88fb-acd1f1596261.png)

The gallery needs additional markup, and ideally needs to sit outside the slider markup itself.

At the moment the slider + gallery is tied together within the lSSlideOuter. Using this doesn't add any class either (when used in your lightSlider+lightGallery example):
```javascript
plugin.lightGallery({
    addClass : 'custome-class'
});
```

**Comment by sachinchoolur** [comment]
Hi,
It is difficult to combine lightGallery and lightSlider. 
lightslider already has thumbnails so why do you need lightGallery thumbnai?

**Comment by martyf** [comment]
Righto my confusion came from how you suggested using addClass to lightGallery in your first example here.

The issue still remains that that the ul (lSPager) that contains the thumbnails has no wrapper around it, and has a width that is controlled by the lSSlideOuter wrapper - the width keeps getting changed by lightSlider itself and the number of slides it includes.

But what if you want to make the thumbnails have a set width (either fixed pixels or percent) and position that does not span the full width of the lightSlider - such as in the example above. 

There's not enough markup to do this - the lSPager ul needs an extra wrapper - it would be great if this level of wrapping could be done by a setting (to add an extra DIV and ID/class) so that the width calculations still work correctly, but this new DIV has the potential to style and size the position of the thumbnails. Refer to the mockup posted earlier here to demonstrate showing 6 thumbnails (out of the collection of X thumbnails) that has a different width and position to the slider itself.
