### ISSUE TITLE
Error in bower package

### ISSUE THREAD

**Issue by kostysh** [sachinchoolur/lightslider#108]
Wrong path:
"main": [
    "lightslider/js/jquery.lightSlider.min.js",
    "lightslider/css/lightSlider.css",
    "lightslider/img/controls.png"
  ]

Should be lightSlider/
or "lightslider" everywhere

**Comment by sachinchoolur** [comment]
Path is already lightSlider/ right? Is their any issue with this?

Thanks.

**Comment by kostysh** [comment]
just tested. new install with: bower install lightslider
Path described in bower.json is "lightslider/js/jquery.lightSlider.min.js"
but real name of folder with sources is "lightSlider"

**Comment by sachinchoolur** [comment]
Hi,
It works fine for me.
Path described in bower.json is "lightSlider/js/jquery.lightSlider.min.js" not "lightslider/js/jquery.lightSlider.min.js" 
Please check bower.json and confirm.

Thanks
