### ISSUE TITLE
Add configuration to either update settings or delete a light slider

### ISSUE THREAD

**Issue by xabikos** [sachinchoolur/lightslider#109]
Currently there is no configuration to update the settings of an initialized slider, e.g. change the mode from slide to fade. On top of this there is no way to delete the slider in order to recreate it. I would really like to have one of these options.

**Comment by sachinchoolur** [comment]
Yes. I will add destroy method soon.

**Comment by corangar** [comment]
:+1: +1

**Comment by xabikos** [comment]
Any update on the issue?

**Comment by groenroos** [comment]
+1 @sachinchoolur

**Comment by plkilroy** [comment]
@sachinchoolur really need a destroy, isactive method like you have with lightGallery

**Comment by usb248** [comment]
Any update, this project seems to be die... :-1: :neutral_face:

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delay..
I have added destroy method in version 1.1.4.. Please check..

**Comment by rocchidavide** [comment]
should destroy() reset also callbacks? Because when I destroy lightslider and rebuild the plugin, lightgallery stops working..

Thank you

**Comment by jagga2105** [comment]
once the lightslider is destroyed and again initilized. then the thumbnail are repeating. (the destroy function is not removing every class and elements added by the lightslider.)

**Comment by richardpoyner** [comment]
For me the destroy remove to much.
I am not sure if it should work like this, but a would love if this could be possible.

`
var slider = $('#lightslider').lightSlider();
slider.destroy();
$('#lightslider').lightSlider();
`

But right now the id lightslider is deleted with the destroy().

**Comment by toniorocks** [comment]
The destroy method is buggy dont work forme, please fix the method

**Comment by TJ-Nityo** [comment]
destroy method has lot of issues. Please help

**Comment by teomanofficial** [comment]
the night is dark and destroy method full of bugs

**Comment by AskDesignTeam** [comment]
dont call the destroy() full of bugs, you need to re_append the template and than restart with lightslider 
```
// reset lightslider
$(element).children('.silder_content').html('<ul><li style="background:red;">item1</li><li style="background:lime;">item2</li></ul>');
// restart lightslider
$(element).children('.silder_content').lightSlider(NewOptionifYouWant);
```

**Comment by toddglidden** [comment]
AskDesignTeam is right.  Before that code, you must backup the html in the ul.  On document ready, do something like:

window.MyCarouselHtmlBackup = $(element).children('.silder_content').html;

Then change the first line above to:

$(element).children('.silder_content').html(window.MyCarouselHtmlBackup);

You may find a more appropriate place to store the backup html than window, but you get the gist of it.
