### ISSUE TITLE
Sluggish window resizing

### ISSUE THREAD

**Issue by pflind** [sachinchoolur/lightslider#111]
Resizing the browser window is sluggish and slow. Tested with Safari 6.2.4 and IE 11.
The problem is because of the monitoring of the window width, I think.

**Comment by sachinchoolur** [comment]
It is required to find window width for enabling responsive option. see the first demo on the website under examples.
Any way resize function calls only after 200 milliseconds after triggering resize event. So normally function gets called after resize or orientationchange event is triggered.
I will try to improve this..
