### ISSUE TITLE
Duplicated thumbnails

### ISSUE THREAD

**Issue by pflind** [sachinchoolur/lightslider#112]
If you set loop:true when using lightGallery(); with the slider, the first and last thumbnails are duplicated.

"All photos (x number)" also counts 2 more photos than there is, because of the two duplicated thumbs.

**Comment by sachinchoolur** [comment]
Hi,
When we set loop:true and mode:'slide' lightslider will duplicate first and last slides for enabling carousel functionality.
All cloned slides will have class `.clone` and all other slides will have `.lslide` class.
You can use lightGallery's selector option to avoid cloned slides.

Ex:
``` html
<ul id="imageGallery">
  <li data-thumb="img/thumb/cS-1.jpg" data-src="img/largeImage.jpg">
    <img src="img/cS-1.jpg" />
  </li>
  <li data-thumb="img/thumb/cS-2.jpg" data-src="img/largeImage1.jpg">
    <img src="img/cS-2.jpg" />
  </li>
</ul>
```
``` javascript
$('#imageGallery').lightSlider({
        gallery:true,
        onSliderLoad: function(el) {
            el.lightGallery({
                selector: '#imageGallery .lslide' // only #imageGallery .lslide will be added in to the lightGallery
            });
        }   
    });
```

**Comment by pflind** [comment]
Yep, that solved it. Thank you!

**Comment by eliseusbcom** [comment]
The plugin is in conflict, when enlarging the image the thumbnails multiply, followed the instructions of configuration and at first it went well, but in looping of the DB they multiply, but the amount of images in the page is correct. many .clones
