### ISSUE TITLE
Thumbnail height problem

### ISSUE THREAD

**Issue by pflind** [sachinchoolur/lightslider#114]
I use `gallery:true` and added a css border around the thumbnails beneath the large photo. But I noticed that my border was cut off at the bottom because the height value is set to the ul thumbnail list:

`<ul class="lSPager lSGallery" style="... height: 57px; padding-bottom: 0%;`

However, if you add `loop:true` the height and padding parameters disappears. Why is that?

I've nailed it down to line 454 in lightslider.js

**Comment by sachinchoolur** [comment]
Hi,
Thank you for pointing this out.
I have fixed this issue..

**Comment by maluco456** [comment]
when i use this slider with only one slide the tumbnail don´t show up.
i'm using this with a dinamic content, and on the begining it will have only one slide, but i realy want to show the thumbnail
how this can be possible
