### ISSUE TITLE
Help Next and Prev

### ISSUE THREAD

**Issue by tijosfx** [sachinchoolur/lightslider#117]
How to put "next" and "prev" controls outside the wrapper div (.lSSlideWrapper)? or custom next and prev controls?

**Comment by sachinchoolur** [comment]
Hi,
You can include custom html for prev and next controls via `prevHtml` and `nextHtml` settings

ex:
``` javascript

$('#light-slider').lightSlider({
    prevHtml : '<span class="custom-prev-html"><img src="custom-prev-img.jpg" /></span>',
    nextHtml : '<span class="custom-next-html"><img src="custom-next-img.jpg" /></span>'
});
