### ISSUE TITLE
'adaptiveHeight' with more than 1 'item'

### ISSUE THREAD

**Issue by jasins** [sachinchoolur/lightslider#119]
Hi,
I am using the slider as a carousal with item set to 2 and slideMove set to 2. The issue is that the adaptiveHeight modifies the height based on the slide number and not the set currently being shown.

Let me explain.

**My settings:**
```
$('#responsive').lightSlider({
        item:2,
        loop:false,
        slideMove:2,
        adaptiveHeight:true,
});
```

- So lets say my slider has 8 slides (each image has a different height)
- So the slides visible are `1 & 2`
- On pressing next slides `3 & 4` are visible
- And so on...

**Issue 1:**
Now when slides `1 & 2` are visible, height is adjusted for **image 1**, *even if image 2 is taller*. Hence image 2 gets cropped.

**Issue 2:**
On 'Next', slide `3 & 4` are visible, but height is set for **image 2**. Now if say image 3 & 4 were both taller than image 2, then both 3 & 4 are cropped.

Hope I make sense. Let me know if you need me to explain this further, and i'll get some screenshots with captions.

Thanks again,
Jasin

**Comment by sachinchoolur** [comment]
Hi,
I think using `adaptiveHeight: true` with multiple slide item would not be a good idea because remaining slides in the viewport may get cropped or display a gap under slider item.

But if you want to use adaptiveHeight with multiple slide item you can use something like this.
``` javascript 
var adHeight = 0;
for (var i = 0; i < settings.item; i++) {
    // check tallest slide in the viewport 
    if ($children.eq(scene+i).outerHeight(true) > adHeight) {
        adHeight = $children.eq(scene+i).outerHeight(true)
    };
};
$el.css('height', adHeight);
```
Please update line number 894 and 983. Please note this code works well only when loop is false.
// From your code sample i can see that you are using loop false

**Comment by jasins** [comment]
Hi Sachin, you rock!

The above code works great as long as slideMove is set to 1

This means issue 1 above is solved, though issue 2 still remains. But I can set slideMove to 1 to take care of it.
And yes, the loop ofcourse has to be set false.

Thanks a lot. Keep up the awesomeness :)

**Comment by RedskyThirty** [comment]
Two years later sorry but for other guys...

Add a new function:

`getHeight: function() {
	var startIndex = (scene * settings.item);
	var endIndex = (startIndex + settings.item);
	var maxHeight = 0;

	if(endIndex >= length)
	{
		startIndex -= (endIndex - length);
		endIndex = length;
	}

	for (var i = startIndex; i < endIndex; i++)
	{
		var height = $children.eq(i).outerHeight();
		if(height > maxHeight) maxHeight = height;
	}
	
	return maxHeight;
}`

And update these lines (sorry I added multiple fixes so my lines numbers are not the same for you):

1. In "setHeight: function() ... var setCss = function() ...", after "if (fade) {}", add this:
`if (settings.item > 1) {
	tH = plugin.getHeight();
}`

2. In "refresh.init = function ()", inside "if (settings.adaptiveHeight === true && settings.vertical === false) {}", change by this:
`if (settings.item > 1) {
	var height = plugin.getHeight();
	$el.css('height', height);
} else {
	$el.css('height', $children.eq(scene).outerHeight(true));
}`

3. In "$el.mode = function (_touch) {}", inside "if (settings.adaptiveHeight === true && settings.vertical === false) {}", change by this:
`if (settings.item > 1) {
	var height = plugin.getHeight();
	$el.css('height', height);
} else {
	$el.css('height', $children.eq(scene).outerHeight(true));
}`

I hope that some of you will win a few minutes or hours ;-)

**Comment by CultureInspired** [comment]
I also have this problem, I don't understand how to apply these fixes discussed in this thread. I tried @sachinchoolur answer by pasting his code into the "onSliderLoad: function() { // code here }" function, but it made no difference.

Any advice?
