### ISSUE TITLE
Auto pause YouTube / Vimeo when slide changes

### ISSUE THREAD

**Issue by onetrev** [sachinchoolur/lightslider#120]
Not sure if this is possible within the super flexible framework for how content is inserted in slides with lightslider, but it sure would be handy and better UX if embeded YouTube or Vimeo videos paused when you moved to the next slide.

Could this be integrated into lightslider, or will this just simple require some custom callback coding to make this work?

**Comment by sachinchoolur** [comment]
Hi,
With default functionality this is not possible But you can do this with the help of callback functions. I have created a jsfiddle demo for you http://jsfiddle.net/sachin377/r3quvf9b/1/
Here is a nice artilce about this https://css-tricks.com/play-button-youtube-and-vimeo-api/

For inserting responsive videos if you want you can refer this article https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

**Comment by onetrev** [comment]
Awesome, thank you! Definitely didn't need to create the fiddle for me, but I really appreciate it and it helps me out for sure. 

It doesn't pause the first video the first time you slide, but I can fix that up I'm sure, no worries.

Thanks again!

**Comment by ctf0** [comment]
thanx for the fiddle but it works only if u slided back to the playing video, so the correct behavior should be when u slide away but for some reason the fiddle didn't work as it should so here is a fix.

everything is the same as the fiddle, just remove the `onBeforeSlide` and change the `onAfterSlide` with the below, also changed `prevSlide` to `current` to avoid confusion.
```js
onAfterSlide: function (el) {
    current = slider.getCurrentSlideCount();
    var youtubePlayer = $('#video li').eq(current - 1).find('.embed-responsive-item').get(0);
    youtubePlayer.contentWindow.postMessage('{"event":"command","func":"pauseVideo","args":""}', '*');
},
```
