### ISSUE TITLE
Image height bug

### ISSUE THREAD

**Issue by pflind** [sachinchoolur/lightslider#121]
Bug #114 also appears to exist when setting a border to the main image.

If you set a css border to the main image the bottom border is cut off, just like it did with the thumbnails before #114 was fixed.

If you set `loop:false` the height is set to the ul `<ul id="imageGallery" class="lightSlider lSSlide lsGrabbing" style="width: 844px; height: 201px; ...`

If you set `loop:true` issue disappears because no height is set to the ul.

**Comment by sachinchoolur** [comment]
Hi,
I have updated lightslider.js 
Please check..

**Comment by pflind** [comment]
Hello,

I'm sorry for late feedback. But yes, the problem is solved now :)

**Comment by kamlesh4k** [comment]
if our first image height is large then our slider height is also large and other images height is small so how i can fix height of slider.
