### ISSUE TITLE
How to specify first slide on init?

### ISSUE THREAD

**Issue by fedotxxl** [sachinchoolur/lightslider#125]
We've got a gallery with option `item: 1`. How to initialize this gallery with opened slide 3 (not first one)?

**Comment by sachinchoolur** [comment]
Hi,
You can use public method `goToSlide(3)`
``` javascript
var slider = $('#lightSlider').lightSlider({
    speed: 0,
    onSliderLoad: function () {
        slider.goToSlide(3);
    }
});
```
Jsfiddle demo :- http://jsfiddle.net/2patspw2/706/

**Comment by fedotxxl** [comment]
What should I do if I need speed = 400? It will have slide animation on init which is strange

**Comment by sachinchoolur** [comment]
Hi,
With current functionality it is not possible. i thought you want to use slide without animation.
for current use you can set `transition-duration : 400ms` once slider is fully loaded.
Please check the jsfiddle http://jsfiddle.net/sachin377/2patspw2/779/
