### ISSUE TITLE
slide counter with multiple slider on one page.

### ISSUE THREAD

**Issue by kidno** [sachinchoolur/lightslider#130]
Hi, I have question to lightslider use.

I use muliple 'lightslider' on one page, this is work well. use class name. not id.
but slide counter is not work.
I refer to examples page(http://sachinchoolur.github.io/lightslider/examples.html), this example case is only one slider on page.
can I slide counter with multiple slider on one page?

thanks. 

![screenshot_548](https://cloud.githubusercontent.com/assets/2646839/7491733/1f94ea3c-f427-11e4-87f7-04ce4a0a66a8.jpg)

**Comment by junkystu** [comment]
You need to use el to limit the slide count elements lookup inside it. In your case, if `.slide_num` is a child of `.imgslider` it will be something like below. Of couse, the lookup will depend on where `.slide_num` sits.
`el.find('.slide_num > .slide_current').text(el.getCurrentSlideCount());`

**Comment by sachinchoolur** [comment]
Hi,
You can use jQuery each function and call each slider for each class separately.

``` javascript
$('.lightSlider').each(function (index) {
    $(this).lightSlider({
        gallery: true,
        item: 1,
        loop: true,
        slideMargin: 0,
        thumbItem: 9,
        onBeforeSlide: function (el) {
            $('#counter' + index).text(el.getCurrentSlideCount());
        }
    });
});
``` 

I have created a jsfiddle demo for you. Please have a look at this link http://jsfiddle.net/2patspw2/1104/
