### ISSUE TITLE
Slider over lapping with the first set of images on Google Chrome web Browser

### ISSUE THREAD

**Issue by JackelsFrog** [sachinchoolur/lightslider#133]
I'm using the light slider on my project and i have used it several times on the same page. And I have noticed that the slider is over lapping with the first set of images. It's like I have fixed those images under the slider. When the second or third set of images come to the screen I can still see the first set of images. The things are happening only when I use the Google Chrome wed browser. Its all ok with the Mozilla Fire Fox, Safari and Internet Explorer. So please help me here to fix this problem.

**Comment by sachinchoolur** [comment]
Hi,
 I am really sorry for the delayed response. I have been quite buy lately.

I think your issue is related to #140. Please check answer.
