### ISSUE TITLE
Controls outside of content slider

### ISSUE THREAD

**Issue by scottquested** [sachinchoolur/lightslider#134]
Hi There,

I would like to have the controls (left & right) outside of the slider which has an overflow hidden.

Is this possible?

Great work btw, love this slider!

**Comment by ramtml** [comment]
yes you can.

1. simply create two left and right div or icons in your document. 
2. initialize slider with lightslider.js with public method. like :- 

    $(document).ready(function() {
        var slider = $('#').lightSlider({
           //plugin options whatever you want
        });
    });

3.  Next initialize those left and right id's or class's like this.
   //for left controll
    $('#left').click(function(){
        slider.goToPrevSlide(); 
    });
    $('#right').click(function(){
        //for right controll
        slider.goToNextSlide(); 
    });

**Comment by scottquested** [comment]
Thank you so much!
