### ISSUE TITLE
Do not work 'auto'.

### ISSUE THREAD

**Issue by vvp24** [sachinchoolur/lightslider#136]
Do not work 'auto' in new version. In old version its work.

**Comment by vvp24** [comment]
jQuery(function($) {
	var autoplay[+id+] = $('#[+id+]').lightSlider({
		autoWidth: true,
		addClass: '[+addClass+]',
		adaptiveHeight: true,
		item: [+items+],
		slideMargin: 10,
		mode: '[+mode+]',
		useCSS: true,
		auto: false,
		slideEndAnimatoin: false,
		keyPress: true,
		controls: true,
		prevHtml: '[+prev+]',
		nextHtml: '[+next+]',
		pager: true,
		enableTouch: true,
		enableDrag: true,
		freeMove: true,
		loop: true,
		slideMove: 1,
		easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
		speed: 400,
		pause: 4000
	});
});
// ]]>
</script>

**Comment by ramtml** [comment]
Hi vvp24,
change 

```javascript
      auto: false
         //into
      auto: true
```

**Comment by vvp24** [comment]
I am sorry this is a typo. Test with auto: true

**Comment by Bram77** [comment]
I've encountered the same issue. Setting auto to true has no effect. I've solved it by using myLightSLider.play() on document ready.

**Comment by miniMAC** [comment]
Do not work

**Comment by evu** [comment]
This might be fixed by doing https://github.com/sachinchoolur/lightslider/issues/143

**Comment by vvp24** [comment]
Thanks

**Comment by sachinchoolur** [comment]
The issue has been fixed. Thanks guys :)
