### ISSUE TITLE
Do not show slide in IE8

### ISSUE THREAD

**Issue by vvp24** [sachinchoolur/lightslider#137]
If auto=false Do not show slide in IE8 until not pressed prev or next.

**Comment by junkystu** [comment]
To build on the above: In IE8, when auto is set to false, the slide will not appear unless manually triggering play via controls or custom triggers.

**Comment by vvp24** [comment]
add "slider.goToNextSlide();". problem solved

**Comment by junkystu** [comment]
@vvp24 That doesn't fix the issue and furthermore, it's a very ugly workaround which causes the image to show up initially, then the slider inits causing the image to hide, then I call `play()` or `goToNextSlide()` and the image reappears.

**Comment by vvp24** [comment]
I agree with you, but I'm not very good at JS.

**Comment by mehany** [comment]
@junkystu Even though it is a an ugly work around for IE8, IE8 is ugly by nature! and any work around for it, i ld say, is accepted regardless ;)

**Comment by g0shed** [comment]
a better workaround is to do a display block important on the css for the active slide on IE8 only, which fixes it

**Comment by junkystu** [comment]
@g0shed Yes, that's doing it, thanks. Good thing I still had that branch lying around however, on IE8, the slider still fades in/out even if there's a single image in the gallery :P

**Comment by sachinchoolur** [comment]
Hi,
I have fixed the issue. It was happening only with fade mode.

Thanks.

**Comment by junkystu** [comment]
@sachinchoolur Thanks for the fix!
