### ISSUE TITLE
auto play issue.

### ISSUE THREAD

**Issue by evu** [sachinchoolur/lightslider#139]
I'm using this and found the auto play function wasn't working.

It seemed to be a problem with checking whether the slide has an image in it:

`obj.has('img')` was finding images even though there was none, so the following code wouldn't execute because no image was loaded. I fixed it by changing it to `obj.find('img').length`.

Line 459

Thought you might want to change it.

**Comment by evu** [comment]
It also doesn't seem to work with vertical mode, moving the if interval check for this.auto to the build init seemed to fix this. Not sure if it's the correct way to go about fixing it though.

**Comment by sachinchoolur** [comment]
I have fixed autoplay issue with vertical mode also. 
Thank you for pointing this out.
