### ISSUE TITLE
Pager & controls visible even with single slide

### ISSUE THREAD

**Issue by scazzy** [sachinchoolur/lightslider#14]
Right now it shows 1 pager bullet, even if just a single slide is present.
Maybe same goes for control buttons

http://i.imgur.com/KIIGamZ.png

How it should work:
Work like a slider as is if more than 1 slides.
If a single slide, let it look like a standalone banner image.

**Comment by zdlldz** [comment]
I'm seeing this issue still in v1.1.6... any ideas?

(Love this js by the way!! Thank you @sachinchoolur !!)
