### ISSUE TITLE
AutoWidth

### ISSUE THREAD

**Issue by marsvieyra** [sachinchoolur/lightslider#140]
Hey! I am using this to display slides (jpg) from a Powerpoint. The thing is that I only see half of the images and cannot figure out for the life of me how to set the with to display the full plicture. Can you hlep me? Thanks so much!!!

**Comment by sachinchoolur** [comment]
Hi,
This is happening because your images are getting loaded only after executing the slider.

One solution is you can wait for all the images to load and the call the slider.
Another method is to set width for all your slide items and then call the slider.

```  html
<!-- if the width of the image is 300px set same width to its container -->
<li style="width:300px"><img src="1.jpg"></li>
```
