### ISSUE TITLE
slider stops after drag

### ISSUE THREAD

**Issue by imezei** [sachinchoolur/lightslider#141]
hello!
i've implemented your lightslider in a project and it is great. there's only one issue.
slider is set to 'auto: true, loop: true', and it works just fine until user drag or click to next/prev slide. then slider just stops. is it possible that slider don't stop after user move to next or prev slide? 
preview: http://www.lajk-restaurant-dubrovnik.com/

**Comment by sachinchoolur** [comment]
Hi,
Please check https://github.com/sachinchoolur/lightslider/issues/109#issuecomment-151569055
