### ISSUE TITLE
Width problem..

### ISSUE THREAD

**Issue by arafay696** [sachinchoolur/lightslider#142]
when i add images in content slider dynamically then width set to 0 to [.content-slider ul ]. how to resolve it?

**Comment by Sentence** [comment]
+1

**Comment by sachinchoolur** [comment]
Hi,
I guess the image is getting loaded after updating the slider.
You can set with of the side item before adding to the slider.

``` javascript
var slider = $('#lightslider').lightSlider();
var newEl = ' <li class="lslide" style="width:300px;"> <a href="javascript:void(0)"><img src="img/cS-1.jpg" /></a> </li>';
$('#lightslider').prepend(newEl);
slider.refresh();
```
