### ISSUE TITLE
Play triggers next rather than resume

### ISSUE THREAD

**Issue by junkystu** [sachinchoolur/lightslider#145]
Calling the play method will navigate instantly to the next slide rather than resume. This issue can be viewed in the [autoplay & pause on hover example](http://sachinchoolur.github.io/lightslider/examples.html#autoplay) by hovering your mouse over the slider rapidly. The slider will loop with the same speed you hover rather than play with the set transition speed and time.

Thanks for the plugin

**Comment by sachinchoolur** [comment]
Hi,
You can put `play()` method inside a `setTimeout` function.

``` javascript
var slider = $('#lightSlider').lightSlider({
    slideMargin: 0,
    item: 1,
    pause: 2000,
    loop: true,
    auto: true
});
var timeout;
$('#lightSlider').on('mouseenter', function () {
    slider.pause();
    clearTimeout(timeout);
});
$('#lightSlider').on('mouseleave', function () {
    timeout = setTimeout(function () {
        slider.play();
    }, 2000);

});
```

Here is the demo http://jsfiddle.net/sachin377/zHfVK/10/
