### ISSUE TITLE
Adding Slides Dynamically

### ISSUE THREAD

**Issue by isaachinman** [sachinchoolur/lightslider#146]
Adding slides dynamically is listed as one of the features of this plugin in multiple places, but never actually discussed (as far as I can tell). Is the intended point that merely adding more DOM elements will add slides?

I have set up a slider that adds more slides when the user is reaching the end of the current array:

    if (currentSlideNumber = allSlides.length - 2) { get more slides }

These new slides are added as img within li, as per the docs. The number of nav dots does not change, and it is not possible to navigate to the new slides. Am I missing something here?

**Comment by isaachinman** [comment]
So after further reading, I was able to dynamically add slides using slider.refresh(). However, the nav dots do not update. Is there a way to get the nav dots working?

**Comment by isaachinman** [comment]
Additionally, the use of refresh seems to cause the transition animation to be bypassed. My function looks like this:

    // AFTER EACH SLIDE TRANSITION, DO THIS
        onAfterSlide: function (el) {

                // WHEN GETTING CLOSE TO END OF SLIDES, ADD MORE
                currentSlide = '#apod' + (window.imgIds.length - 3);
                if ($(currentSlide).parent().hasClass("active")) {
                    generateNewSlides();
                    window.slider.refresh();
                };

            },

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response .
You have to add class `lslide` to your new slide item. I have updated the example on the demo website.

**Comment by isaachinman** [comment]
Which example? I don't see it anywhere on [this page](https://sachinchoolur.github.io/lightslider/examples.html).

**Comment by sachinchoolur** [comment]
Please check the [Public Methods](https://sachinchoolur.github.io/lightslider/examples.html#relBlock) section.

When you click on the` add slide` button new slide getting added to the slider

**Comment by isaachinman** [comment]
Ah, I see. Cheers.

**Comment by christophfranke** [comment]
I have noticed, that even with adding the lslide class to the new slide, transitions are ignored for about a second. I have located the problem in around lightslider.js:920 with the 'lSSlide' class being added with a delay of a second. I have changed this and instead add the class inside a jQuery ready handler on the slider and also make sure to trigger the slide transition inside a ready handler on the slider. This solves the problem for me, but I am not sure if it does in general, because I don't know the reason for the one second delay in the first place (I also do not see any reason for it in the code).

**Comment by alimzhanovamir** [comment]
@sachinchoolur , Answer please! Why did you add a delay before adding lSSlide or why was it deleted?
 I had to redefine the lSSlide styles. 

In order not to correct the js file, I override the styles.
`<ul class="custom-carousel">`

`.lSSlideWrapper .custom-carousel`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`-webkit-transition: all 1s`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`-webkit-transition-property: -webkit-transform,height`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`-moz-transition-property: -moz-transform,height`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`transition-property: transform,height`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`-webkit-transition-duration: inherit !important`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`transition-duration: inherit !important`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`-webkit-transition-timing-function: inherit !important`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`transition-timing-function: inherit !important`
