### ISSUE TITLE
Destroy Method

### ISSUE THREAD

**Issue by dcollings** [sachinchoolur/lightslider#147]
Is there a destroy method for Lightslider?

I'm using it within another jQuery plugin that expands a hidden piece of content. Lightslider loads perfectly first time round but when the content is closed and reopened it's broken.

I'd like to be able to destroy the slider on content close if possible.

**Comment by sachinchoolur** [comment]
Hi currently destroy method id not available. But you can refresh slider with `refresh()` method.

``` javascript
var slider = $('#lightslider').lightSlider();
slider.refresh()
```

**Comment by boban-radeski** [comment]
But how to destroy the slider, there is a lot of situations where we have to destroy it. How to do that?

**Comment by cevena** [comment]
Same problem i face and when i use slider.refresh script says undefine function slider.refresh

error: Uncaught TypeError: slider.refresh is not a function
    at HTMLDivElement.<anonymous>

 $(document).ready(function() {
	var slider = $(".content-slider").lightSlider({
		loop:false,
		keyPress:true,
		verticalHeight:500,
		item:1,
		auto:false,
		adaptiveHeight: true,
		enableTouch: true,
		enableDrag: false,
		freeMove:true,
	});

	$('.save-note').click(function() {
		$(this).closest('.col-sm-12').find('.note-section').removeClass('hide').fadeIn('slow');
		slider.refresh(); 
    });
});
