### ISSUE TITLE
 Main field is missing from package.json

### ISSUE THREAD

**Issue by Dimasdanz** [sachinchoolur/lightslider#148]
I install lightslider using npm since I used browserify.
I don't know if this is intentional or not, but "main" field is missing from package.json thus "require-ing" it would return module not found.

Adding it manually will work thou
`"main":"dist/js/lightslider.js" `

It will look like this
```json
{
  "name": "lightslider",
  "main": "dist/js/lightslider.js",
  "description": "jQuery lightSlider is a lightweight responsive content slider - carousel with animated thumbnails navigation",
...
}
```

or
```js
require('../node_modules/lightslider/dist/js/lightslider.js');
```
also works.
But would it be nicer if it's included already?

Thanks.

**Comment by sachinchoolur** [comment]
Sorry for the delayed response.. 
I have added main field..
