### ISSUE TITLE
margin for UL should be set to 0

### ISSUE THREAD

**Issue by joncas** [sachinchoolur/lightslider#149]
Hello, and many thanks for a great slider !

In using it within a Wordpress page, I found that Wordpress's css definition with a left margin  for UL causes the images in the slider to be offset.

Adding 
ul.lightSlider {margin:0;}

after your core definitions in the CSS fixes it.

Here you can see a sample without fix:
   http://ateliersinople.com/L2.html
(after the second slide passes, a slice of the first one remains visible on the left)

Here it is with the fix:
  http://ateliersinople.com/L1.html

![screen](https://cloud.githubusercontent.com/assets/3637307/8632624/25682572-27a4-11e5-8040-b61bf506bffe.PNG)

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response..
I have fixed this issue ..
