### ISSUE TITLE
Slider weird bug when resizing/changing window

### ISSUE THREAD

**Issue by mathamel** [sachinchoolur/lightslider#150]
I have a weird issue with lightslider, I created a vid so you can review the behavior.

https://www.youtube.com/watch?v=3VD1kVIm794

**Comment by sachinchoolur** [comment]
Hi,
Thanks for the video. I have never experienced such an issue. Could you please share your website url . It is not completely visible in the video.

Thanks.

**Comment by mathamel** [comment]
Hi, 

 

This was on development server, we have change slider script to owl carousel. I’ll still try to send you code when I find time next week.

 

Mathieu Hamel

Président | Développeur Web

 <http://manaweb.ca/> manaweb.ca | 438.490.2115

**Comment by sachinchoolur** [comment]
Ok.
Please reopen the issue if you found it again..
