### ISSUE TITLE
Switching from gallery to pager on breakpoint

### ISSUE THREAD

**Issue by denkmalimmo** [sachinchoolur/lightslider#151]
**A small responsive issue:** when switching from `gallery: true` to `gallery: false` on a breakpoint, the markup changes accordingly, but the CSS-classes remain untouched. This results in the gallery-specific styles being falsely applied to the dots-pager (and vice versa) when resizing the viewport.

**JsFiddle:**
http://jsfiddle.net/eu00ygdm/
**Fullscreen:**
https://jsfiddle.net/eu00ygdm/embedded/result/
(resize from initial full-width to small width, then refresh page to see the expected result)

*Expected result:*
CSS-Class `lSGallery` toggled to `lSpg `, dot-style pager appears on viewport-resize

*Experienced result:*
CSS-Class remains the same, wrong CSS-Rules applied

**Comment by sachinchoolur** [comment]
Hi,

Sorry for the delayed response.
Currently lightslider responsive feature supports only `item`, `slideMove`, `slideMargin`, `thumbItem`, and  `thumbMargin` properties.

But here is a work around for your problem. I have done it with css media queries. http://jsfiddle.net/eu00ygdm/1/.
