### ISSUE TITLE
Can't get freeMove to work in any setting

### ISSUE THREAD

**Issue by BrushyAmoeba** [sachinchoolur/lightslider#152]
As I understand it, freeMove:true allows intermediate scrolling (will not snap to nearest item). 

I tried to enable this on a project of mine and nothing was happening. After a while of messing around I decided to just try to get freeMove working in the lightslider demo, and even that I couldn't do. 

Is my understanding of what freeMove does just wrong or do I need to do something different to enable freeMove? I was able to change all the other settings but can't seem to get freeMove to work no matter what. In the settings page, it says that freeMove only takes effect when using touch or drag but even with one/both of those enabled I didn't observe any changes. I considered that it could be conflicting with other settings but even when disabling other settings (except enableTouch and enableDrag) I didn't see any changes.

Thanks

**Comment by sachinchoolur** [comment]
Hi,

If loop is false you will not be able to swipe or drag the first/last slide in opposite direction without enabling `freeMove`. If freemove is true you are free to swipe or drag the last/first slide upto some extend.

You can compare the jsfiddle links to understand the freeMove functionality.
1) http://jsfiddle.net/2patspw2/1153/
2) http://jsfiddle.net/2patspw2/1154/

Drag or swipe the first slide from left to right ..

I know the documentation is not clear enough. I will update when i get time.

Thanks.
