### ISSUE TITLE
Using loop and slideMove together

### ISSUE THREAD

**Issue by Valencia2014** [sachinchoolur/lightslider#153]
Using this code:

  $(document).ready(function() {
var slider = $('#lightSlider').lightSlider({
    item: 4,
    autoWidth: false,
    pause: 5500,
    slideMove: 4,
    mode: "slide",
    loop: false,
    slideMargin: 2,
    keyPress: true});
});

whenever I make loop true, the slideMove will only let me move forward by one instead of 4. As soon as I make loop: false, the slide moves by 4.

Edited to add an example and this is forked from the jsfiddle on the website made for this:
http://jsfiddle.net/L5fn5vb0/

**Comment by Valencia2014** [comment]
So I figured out the problem starts at line 225 in your code:
                if (settings.loop) {
                    settings.slideMove = 1;
                    settings.freeMove = false;
                }
Why do you even need that?? I just removed line 226 and it's working fine.

**Comment by sachinchoolur** [comment]
Hi,
Currently `slidemove` will be converted into 1 if you set loop true.

**Comment by isaachinman** [comment]
@sachinchoolur But why? Surely it's trivial to loop with slideMove > 1? I'd like to be able to use slideMove:2 and loop:true at the same time.

**Comment by panfanky** [comment]
probably because loop creates ".clones", it would have to create more clones at a time.. But it would be a nice improvement.

**Comment by timint** [comment]
Why not make it scroll back to 1 when it reaches the end?
