### ISSUE TITLE
Flash of slides on load

### ISSUE THREAD

**Issue by robgnyc** [sachinchoolur/lightslider#157]
Using your slider on this page:

http://meridian.mediumstudios.com/project-activity/arbor-woods/

It handles a Google map very well.

However I made two additional slides with red and blue backgrounds just to test what it will do with subsequent slides and I see a flash of the red and blue when it loads.

I'm not quite sure if this is a settings issue or a bug. At first I thought it was due to the loading of the map but it happens on pages with just red and blue slides as well:

http://meridian.mediumstudios.com/project-activity/ashville-park/

Thanks.

**Comment by janice171** [comment]
I have the same issue on one site. Is there a loader than can be added perhaps?
(great slider by the way)

**Comment by sachinchoolur** [comment]
Hi,
Please have a look at issue #19 . You could use the same solution.
@janice171 I will try to add a loader in the next major version..
