### ISSUE TITLE
Slider does not resume after changing the slide manually

### ISSUE THREAD

**Issue by rahulneve2far** [sachinchoolur/lightslider#159]
Hi there,

Great work with the slider. There is only one thing I can not seem to figure out.

I have set the slider to 'auto: true, loop: true'. When I drag or click to next or previous slide, the slider stops and does not resume sliding.

Is there any way to force the slider to resume after manually browsing through the slides? Please help me out on this.

Thanks much,
Rahul

**Comment by sachinchoolur** [comment]
Hi,
I have fixed the issue.. Please use latest files..
