### ISSUE TITLE
Position not reset after refresh

### ISSUE THREAD

**Issue by JonWallsten** [sachinchoolur/lightslider#160]
I use this slider with Angular for a product list. When I filter the list I refresh the slider.
However, if you have already used the slider to go right, and the next category you pick doesn't have as many items, you have a problem. The slider's translate3d value is not refresh thus you don't see any items on screen.

**Comment by coax** [comment]
You need to return slider to first slide before refreshing, eg.:

    ...
    slider.goToSlide(0);
    slider.refresh();
