### ISSUE TITLE
YouTube button unexpected behavior

### ISSUE THREAD

**Issue by Prod10mm** [sachinchoolur/lightslider#163]
I have encountered an issue where clicking on a play button on aYouTube video in a slide exhibits unexpected behavior. 

The first slide will work correctly, but clicking on the play button on any other slide will move the player instead of playing the video. On slides other than the first, if you click the video not on the play button, it will play, but clicking the play button messes up the position of the slider.

Here is a jsfiddle set up with youtube videos in the slider:
http://jsfiddle.net/Prod10mm/3kL3n913/2/

I am only seeing this issue in Chrome, it does not appear to be an issue on Safari or Firefox.

**Comment by sachinchoolur** [comment]
Hi,
I am not sure what the issue is.. But adding useCSS: false fixed the issue.. 
Here is the updated jsfiddle http://jsfiddle.net/3kL3n913/4/
