### ISSUE TITLE
How to destroy() after adding?

### ISSUE THREAD

**Issue by hiralatcal** [sachinchoolur/lightslider#164]
Thank so much. How do I remove the lightSlider from an element, after it's added by doing something like $("#mydiv").lightSlider() ? 

In my case I add the slider to a div then replace it's content with something else like a YouTube video, then load different photos again that I want to apply lightSlider() to.

**Comment by sachinchoolur** [comment]
Hi,
Please check https://github.com/sachinchoolur/lightslider/issues/109#issuecomment-151569055

**Comment by hiralatcal** [comment]
Sweet. Thanks so much for following up on this.
