### ISSUE TITLE
Loop:true, not working!!!!

### ISSUE THREAD

**Issue by sLippitt** [sachinchoolur/lightslider#168]
Hey, 

Following your docs it states to make the slides return to the beginning you need to add loop:true to the options. I've done this and it's still not looping. Can someone help please?

<script type="text/javascript">
   $(document).ready(function() {
    $('#imageGallery').lightSlider({
        gallery:true,
        item:1,
        thumbItem:5,
	loop:true,
        thumbWidth:1000,
		auto: true,
		speed: 600,
		pause: 4000,
        slideMargin:0,
		loop:true,
        enableDrag: false,
        currentPagerPosition:'left',
        onSliderLoad: function(el) {
            el.lightGallery({
                selector: '#imageGallery .lslide'
            });
        }   
    });  
  });
</script>

http://bluemoontesting.co.uk/carltonsmith/

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response. 
It seems to be working on your website..

**Comment by sLippitt** [comment]
Hi Sachin,

Thanks for getting back to me. The looping problem exists when activating the light gallery. Can you point me to a solution?

Kind Regards,
Shaun
___________________________

Shaun Lippitt

Web Developer, Blue Moon Creative Ltd.
Winner, Skills Funding Agency National Small Employer of the Year 2014/15
Winner, RAR ‘On Time’ award 2015
A City & Guilds Top 100 Employer

Mobile: +44 (0)777 586 1718
Pershore: +44 (0)1386 555 666
London: +44 (0)20 7183 2636
www.bluemooncreative.co.uk<http://www.bluemooncreative.co.uk/>

36 High St. Pershore, Worcs WR10 1DP
61 Berners St. London W1T 3NJ
___________________________

ISO9001 no. GB2004462
___________________________

This communication contains information which is confidential, and is for the exclusive use of the addressee(s). If you are not a named addressee please contact the sender immediately, and also delete the communication from your system. Any views or opinions presented are solely those of the author and do not necessarily represent those of Blue Moon unless otherwise specifically stated. We cannot accept any responsibility for viruses, so please scan all attachments.

We are always looking at ways to improve  our services. If you have any feedback, please let us know.

**Comment by sachinchoolur** [comment]
Hi,
You can refer  #112
