### ISSUE TITLE
Load images with Ajax?

### ISSUE THREAD

**Issue by LuizPerez** [sachinchoolur/lightslider#17]
I'm trying to use lightslider loading images with Ajax and JQuery.
Can I do this?
Send a ajax peticion to a php script and load the response (Array of <img>) in the div to add the images to the slider?
Thanks.

**Comment by User0816** [comment]
How would _data_ look like? I cannot imagine the data structure ...

**Comment by AkhilLabGlo** [comment]
I am retrieving images from backend in jquery ajax success. I need to bind the images into lightslider and display it. For this I initialised like shown above and refreshed in the success function. But slider is not working. I am using v1.1.3 version.

**Comment by youssefboudaya** [comment]
i'm appending multiple images to my lightslider element do i have to refresh with every append action ?
