### ISSUE TITLE
float slides render bad until the slider is initialized

### ISSUE THREAD

**Issue by scazzy** [sachinchoolur/lightslider#19]
as you know your plugin uses float method to keep the slides alinged, and when the slider is initialized, you are able to give width to the parent container via javascript.

BUT... until the slider is loaded, the slides are stacked one below the other, as like normal elements, blocking space, and once the slider is init-ed, they suddenly go up and form a slider stacking one beside each other.
This wouldn't be noticed if its a single slider on page, but if thee's other content (big page) along with the slider, or consider a slow connection, the slider wouldn't be loaded the moment you enter the page. hence, the awkward rendering or movement, whatever you call, appears.

solutions: 
1. for sliders I prefer to use absolute, so your slider looks as is before and after slider is loaded because of CSS, blocking same position before and after.
1. giving fixed height to the slider and overflowing none, is a way - but we talk responsive here, so isn't a good idea.

What do you think?

**Comment by SimranMalhotra** [comment]
Stacking of slides issue solved after adding cS-hidden class.  But I am getting slider like this after including cS-hidden. 

Before loading 
![screenshot_2018-12-15 pws store 1](https://user-images.githubusercontent.com/21124318/50039442-bbd60c00-0058-11e9-8596-1143d2c5ae83.png)

After loading
![screenshot_2018-12-15 pws store](https://user-images.githubusercontent.com/21124318/50039419-3b171000-0058-11e9-8fc7-64422ef13013.png)

How can I solve this issue? Please guide.

**Comment by SimranMalhotra** [comment]
Including my script inside ` $(window).load(function(){});` solved the issue shown in first screenshot. But i am still getting double lsaction as shown in the second screenshot.
