### ISSUE TITLE
How to set height image

### ISSUE THREAD

**Issue by NSLog0** [sachinchoolur/lightslider#255]
I want to set height of image I have issues like below image, So I want to set image height around 100px or something like that, Any suggestion 
![screenshot from 2016-06-11 23-45-30](https://cloud.githubusercontent.com/assets/1640817/15986321/80e34dfc-302f-11e6-9f57-3f68528f2cf5.png)

**Comment by avatarr** [comment]
@sachinchoolur

**Comment by NSLog0** [comment]
No support, closed
