### ISSUE TITLE
Check if slider is already initialized

### ISSUE THREAD

**Issue by VeeK727** [sachinchoolur/lightslider#290]
I have a function whose callback is the initialization of lightslider. Normally I'm expecting this function to only execute once but in any case the function is executed more than once, lightslider gets re-initialized. This produces multiple pagers at the bottom (all working).

So is there a way to check if lightslider is initialized before and if not, initialize it. Here's the code that I have:

```
$('#split-form-trigger').leanModal({
    ready: function() {
      $('#split-form').lightSlider({
	item: 1,
	speed: 500,
	controls: false
      });
    }
  });
```

**Comment by microcipcip** [comment]
I don't know leanModal but you could just use a variable
```
var isLightSliderInitialized = false;
$('#split-form-trigger').leanModal({
    ready: function() {
      if (isLightSliderInitialized) return;
      $('#split-form').lightSlider({
	item: 1,
	speed: 500,
	controls: false,
        onSliderLoad: function(el) { isLightSliderInitialized = true; }
      });
    }
  });
```

**Comment by VeeK727** [comment]
@microcipcip Thanks mate. That was excellent. By the way leanModal was a function to trigger a modal/popup
