### ISSUE TITLE
How to increase the size in LightGallery when clicking on div light slide.

### ISSUE THREAD

**Issue by yongwc2710** [sachinchoolur/lightslider#292]
How to increase the size in LightGallery when clicking on div light slide.
`       <script type="text/javascript">
            $(document).ready(function() {
            $('#lightgallery').lightSlider({
                    gallery: true,
                    item: 1,
                    loop: true,
                    thumbItem: 8,
                    slideMargin: 0,
                    enableDrag: false,
                    speed: 1000,
                    auto: true,
                    loop: true,
                    currentPagerPosition: 'left',
                    onSliderLoad: function(el) {
                        el.lightGallery({
                        selector: '#lightgallery .lslide'
                        });
                    }
                });

            });
</script>`
![image](https://cloud.githubusercontent.com/assets/21030905/20611253/bee98834-b2fa-11e6-8687-54e3713c2b9a.png)

i want something look like this...
![image](https://cloud.githubusercontent.com/assets/21030905/20611259/dfe40a96-b2fa-11e6-9a35-27be88ad4ede.png)

Please help!

**Comment by sajpasa** [comment]
your image needs to be big enough. Can you add your html code. 
If you have 2 version of the image then you can add the bigger version to the gallery callout link. See below-
`<ul id="imageGallery"><li data-src="big image link">
                    <img src="small image link">
                  </li></ul>` 

If you only have one version of the image throughout then it will appear as you want it if the image is big enough.
