### ISSUE TITLE
Pass captions to lightGallery from lightSlider

### ISSUE THREAD

**Issue by clarkedesign** [sachinchoolur/lightslider#316]
I have a combined gallery using lightGallery and lightSlider.

Captions display as expected in lightSlider, but they do not get passed through into lightGallery when a photograph is clicked to activate the lightbox gallery.

is there a parameter I am missing ?

`<ul id="imageGallery">

    <li data-thumb="images/gallery/thumbnail/gallery-1.jpg" data-src="images/gallery/large/gallery-1.jpg">
        <img src="images/gallery/large/gallery-1.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-2.jpg" data-src="images/gallery/large/gallery-2.jpg">
        <img src="images/gallery/large/gallery-2.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-3.jpg" data-src="images/gallery/large/gallery-3.jpg">
        <img src="images/gallery/large/gallery-3.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-4.jpg" data-src="images/gallery/large/gallery-4.jpg">
        <img src="images/gallery/large/gallery-4.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-5.jpg" data-src="images/gallery/large/gallery-5.jpg">
        <img src="images/gallery/large/gallery-5.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-6.jpg" data-src="images/gallery/large/gallery-6.jpg">
        <img src="images/gallery/large/gallery-6.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-7.jpg" data-src="images/gallery/large/gallery-7.jpg">
        <img src="images/gallery/large/gallery-7.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-8.jpg" data-src="images/gallery/large/gallery-8.jpg">
        <img src="images/gallery/large/gallery-8.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-9.jpg" data-src="images/gallery/large/gallery-9.jpg">
        <img src="images/gallery/large/gallery-9.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-10.jpg" data-src="images/gallery/large/gallery-10.jpg">
        <img src="images/gallery/large/gallery-10.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-11.jpg" data-src="images/gallery/large/gallery-11.jpg">
        <img src="images/gallery/large/gallery-11.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>
    <li data-thumb="images/gallery/thumbnail/gallery-12.jpg" data-src="images/gallery/large/gallery-12.jpg">
        <img src="images/gallery/large/gallery-12.jpg" data-sub-html=".caption">
        <div class="caption"><h3>Photograph Title</h3>
            <p>Photograph description</p>
        </div>
    </li>

</ul>`

`<script>
  $(document).ready(function () {
    $('#imageGallery').lightSlider({
      gallery: true,
      item: 2,
      loop: true,
      thumbItem: 8,
      slideMargin: 10,
      auto: true,
      pause: 4000,
      speed: 1000,
      pauseOnHover: true,
      currentPagerPosition: 'left',
      onSliderLoad: function (el) {
        el.lightGallery({
          selector: '#imageGallery .lslide',
          download: false,
          subHtmlSelectorRelative: true
        });
      }
    });
  });
</script>`

**Comment by caessard** [comment]
It is not a issue, just configuration. Remove subHtmlSelectorRelative property, create a div of each caption outside of gallery using 
```
<div id="caption_{item.uid}" style="display:none">
	<h4>{item.title}</h4><p>{item.description}</p>
</div>
```
And in the data-sub-html attribute set each caption "#caption_{column.media.uid}"
