### ISSUE TITLE
Text in slide is not selectable

### ISSUE THREAD

**Issue by Tashows** [sachinchoolur/lightslider#331]
Was just trying that on my app. When there is text in a slide, you cannot select it. Tried it in a very basic jsfiddle, where drag and touch settings are disabled.

https://jsfiddle.net/8przencr/2/

Not that big of an issue, I just happened to want to select something and realized I couldn't. It could be an option if drag is disabled. As always awesome plug in!

**Comment by yash2code** [comment]
same issue

**Comment by Tashows** [comment]
Just encountered that problem again and looking in google led to my reported issue here. I thought I might as well bump it?

**Comment by Tashows** [comment]
I was just revisiting my open issues. For anyone that might come across this, an easy solution could be to add:
```
.lSSlideOuter {
  user-select: initial;
}
```
This will still not work when drag is enabled, which is of course expected.
[https://jsfiddle.net/zsw024rn/](https://jsfiddle.net/zsw024rn)
