### ISSUE TITLE
slider is not working perfectly on a modal

### ISSUE THREAD

**Issue by thakurdivendra** [sachinchoolur/lightslider#340]
lightslider in not working on a modal why?
i am using bootstrap modal but it will not taking its actual height until i am not click somewhere else f.g. development tools

**Comment by omguddu100** [comment]
I am also tried with bootstrap modal, It not trigger but when resize browser then it's load..

**Comment by thakurdivendra** [comment]
just refresh the lightslider with global functions refresh().  on click event of open modal

**Comment by kylefoo** [comment]
@thakurdivendra  is right, default modal behavior will make display: none; Thus, I overwritten the default modal css as followed:

`  .ui.modal {
    display: block;
    visibility: hidden;
  }`

If you have multiple modal, I suggest doing dynamic ids assignment of slider and initialize it via loop.

javascript:
`    function initSlider(sliderId) {
      $('#'+sliderId).lightSlider({
        item:2,
        loop:true
      });
    }
    
    $('.ui.modal').each(function(i){
      initSlider('lightSlider_'+(i+1));
    });`

**Comment by omguddu100** [comment]
I fixed this issue by window resize method. 
i don't know this is better approach or not.

---------------------------------------
$("documents").on("click", ''.loadslider",function(){
   $(window).resize();
   $(window).resize();
   });
   ------------------------------------
<ul class="lightSlider">
        <li data-thumb="http://sachinchoolur.github.io/lightslider/img/thumb/cS-1.jpg">
            <img src="http://sachinchoolur.github.io/lightslider/img/cS-1.jpg" />
        </li>
 </ul>
-------------------------------
  $(document).ready(function() {
     $('.lightSlider').lightSlider({
         gallery: true,
         item: 1,
         loop: true,
         slideMargin: 0,
         thumbItem: 6,
         onSliderLoad: function() {
             $('.lightSlider').removeClass('cS-hidden');
         }
     });

     $(".loadslider").click(function() {
         $(window).resize();
         $(window).resize();

     });
 });
-------------

**Comment by youssefboudaya** [comment]
i'm facing the same problem this is my code :
`jQuery("#image1").empty();
 var ul = jQuery("<ul id='lightSlider_ap'></ul>");
jQuery.each(data[0]['imgs'], function(key, value) { //loop through it
var img = "{{URL::to('/')}}/"+value.path;
 var li = jQuery("<li><img  src='"+img+"' width='200' height='200' /></li>")
ul.append(li);
});
jQuery("#image1").append(ul);
ul.lightSlider();
jQuery('#image1').show();`

**Comment by ghost** [comment]
My solution was to have gallery plugin trigger the display function in a container before firing another function, in my instance, to hide the gallery container. This meant that for a fraction of time while the page is loading you can see the gallery before it is hidden to be later accessed by an action.

`$(window).on('load', function(){`
`$('.gallery').lightSlider();`
`$('.gallery').toggle();`
`})`

**Comment by omguddu100** [comment]
Okay thanks .

**Comment by parasiteDev** [comment]
enough solutions for this issue so i am closing it

**Comment by RohanKambleDev** [comment]
Refresh worked for me

<img width="588" alt="Screenshot 2022-01-19 at 10 10 19 PM" src="https://user-images.githubusercontent.com/968285/150175228-86f831bd-78a3-4253-a7f4-601c138fb3a6.png">

where **propertyPreview.lightSlider** is having the object of **lightSlider**

`propertyPreview.lightSlider = $('#property-gallery-js').lightSlider({
...options
});`

and `$('#property-gallery-js')` is the selector of the element used for media slide show

Hope this helps someone.
