### ISSUE TITLE
I don't want thumbnail nor those .... bellow

### ISSUE THREAD

**Issue by bosz** [sachinchoolur/lightslider#386]
I want a simple slider without thumbnail nor the dots bellow. 

Please, how do i do that?

**Comment by bosz** [comment]
Help wanted.

**Comment by smartcorestudio** [comment]
`pager: false`

**Comment by bosz** [comment]
wow, so far, this is the best community I've met. Timely response, solves my problem. 

Thanks @smartcorestudio .
