### ISSUE TITLE
Jquery mousedown/touchstart can't be triggered if item amount is not enough for dragging.

### ISSUE THREAD

**Issue by neilliang** [sachinchoolur/lightslider#396]
I'm facing a weird bug. If the item amount(or width ) is not enough for dragging, then mousedown/touchstart event won't be triggered. But, mousemove/touchmove and mouseup/touchend work fine. I'm using the option autoWidth:true and dymalically calculate the width to fill the container with 5 pieces of items. If the item amount less than 5, the item can't be dragged and then the bug happens. 

My temporarily way to solve this is give the container one more invisible item and then everything works fine.

**Comment by coax** [comment]
I'm having an exact issue (this is responsive/mobile related issue). How did you solve it (aside this nasty hack which I cannot use because sometimes I have only 1 item)?

**Comment by neilliang** [comment]
If item amount is not enough, just append some invisible items before create lightslider object. I havn't found any other solution yet.
