### ISSUE TITLE
Fade function

### ISSUE THREAD

**Issue by reception-zz** [sachinchoolur/lightslider#41]
Perhaps not really an issue but more of a request...

The fade function right now fades in a slide while the previous one is directly hidden, resulting in a bit of a 'shocky' effect. I guess it would be better if the next slide is fading in on top of the other slide. Afterwards the previous slide can be hidden. 

Is this possible right now?

Thanks!

**Comment by fredboyle** [comment]
In case anyone has issues with the sudden jerky results of the crossfade a bit of messing around has led to the discovery that the `lSSlideWrapper .lSFade > *.active` that suddenly changes the z-index appears to be the culprit.

Commenting that out leads to a more natural crossfade.
