### ISSUE TITLE
Click event issue on ipad

### ISSUE THREAD

**Issue by codewp** [sachinchoolur/lightslider#421]
Hi,

I have an issue with click events on iPad when `item > 1`. but it is OK on iPhone.
![lightslider-auto-width-disabled-click-issue](https://user-images.githubusercontent.com/10684451/50821566-be204300-1344-11e9-9886-e3fb05ed6b19.gif)

When I set `item: 1, autoWidth: false` it works properly.
![lightslider-auto-width-disabled](https://user-images.githubusercontent.com/10684451/50821628-ee67e180-1344-11e9-97de-96b3e35f6d4e.gif)

Also, I should say that click event triggers on `<a>` tag.

Please let me know how can I fix this problem?

Thanks.

**Comment by parasiteDev** [comment]
you are using either fancybox or lightslidebox, for zomm the image. it is a cause of that plugin not the lightslider 
Thanks.

**Comment by codewp** [comment]
Yes I found that it is related to the slider plugin but I forgot to close this issue.

Thanks
