### ISSUE TITLE
currentPagerPosition option is not working

### ISSUE THREAD

**Issue by fzhukov** [sachinchoolur/lightslider#43]
I'm trying this configuration for slider on demo page

``` javascript
gallery:true,
item:1,
vertical:true,
verticalHeight:295,
vThumbWidth:50,
thumbItem:3,
pager:true,
thumbMargin:4,
slideMargin:0,
currentPagerPosition:'left'
```

but thumbs not move to left side of vertical slider..  Maybe I do something wrong or I don't understand this option right?

**Comment by p0rsche** [comment]
Have the same issue. I'm using RTL.
