### ISSUE TITLE
[BUG] mode: 'fade' calculation of image hight is wrong on smaller screens

### ISSUE THREAD

**Issue by ste101** [sachinchoolur/lightslider#46]
In line 222 (`'padding-bottom': ($children.height() * 100) / elSize + '%'`) and 228 calculation is wrong on smaller screens because `$children.height()` does not get the correct height of the resized image.
You will see it if you initialize lightslider at `$(window).load(function()`.
Initializing at `$(document).ready` works most of the time in Firefox and Chrome although the `$children.height()` get the wrong value but not in IE11

**Comment by ste101** [comment]
Hello Sachin, did you try my test site?

**Comment by sachinchoolur** [comment]
Sorry i missed your message. Thanks for the demo.
As you said it is giving wrong height in IE11 on small screens.
Let me check this issue.

**Comment by ste101** [comment]
Any news about this problem? I would need a solution?

**Comment by sachinchoolur** [comment]
Hi,
Once again sorry for the delay. I was busy with some work.
I have created a demo for you. Please check this url. http://jsfiddle.net/LbuhdaeL/ 
It works for me. You have to use the code from the jsfiddle and set adaptiveHeight: true
``` javascript
$("#lightSlider").lightSlider({
    item: 1,
    mode: 'fade',
    auto: true,
    loop: true,
    pause: 6000,
    speed: 2000,
    controls: false,
    adaptiveHeight: true
});
```
