### ISSUE TITLE
Image Zooming

### ISSUE THREAD

**Issue by ghost** [sachinchoolur/lightslider#47]
Hi

Great slider one of the best I've used! However are there any plans to add in image zoom functionality or whether it's possible to integrate with any other image zoom scripts out there? Something like jQuery Zoom.

Thanks

**Comment by elyorwill** [comment]
some how it is working only on mobile, not on desktop.

**Comment by souvik-dev-git** [comment]
Fancybox stops working if added zoom feature. Do you have any solution for it?
