### ISSUE TITLE
Lightslider is not working with Lightgallery V2

### ISSUE THREAD

**Issue by maffintos** [sachinchoolur/lightslider#486]
The versions that I have used are:
 - Lightgallery 2.7.1 (latest umd)
 - Lightslider 1.1.6 (latest)

This is how i called the function: 

`$('#imageGallery').lightSlider({
	gallery:true,
	item:1,
	loop:true,
	thumbItem:9,
	slideMargin:0,
	enableDrag: false,
	currentPagerPosition:'left',
    onSliderLoad: function(el) {
                    el.lightGallery({
                        selector: '#lightSlider .lslide'
                    });
   }   
});  `

And this is the error message that I received: "Uncaught TypeError: el.lightGallery is not a function
    at onSliderLoad"

I think the v2 version of Lightgallery cannot be called in Lightslider anymore, but v1 works perfectly fine. Please, test it yourselves too!

**Comment by sachinchoolur** [comment]
The code that you use to initialize lightGallery is not correct. 

it should be 

```js
// lightSLider returns jQuery element 
lightGallery(el[0], {
                selector: '#imageGallery .lslide'
            });

```

full example 

```js

$('#imageGallery').lightSlider({
	gallery:true,
	item:1,
	loop:true,
	thumbItem:9,
	slideMargin:0,
	enableDrag: false,
	currentPagerPosition:'left',
 onSliderLoad: function(el) {
           lightGallery(el[0], {
                selector: '#imageGallery .lslide'
            });
        }   
});  
```

Working demo - https://codepen.io/sachinchoolur/pen/jOeOjgw

**Comment by maffintos** [comment]
It works, thank you very much!
