### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by wpexplorer** [sachinchoolur/lightslider#56]
I wish to donate, but I didn't see any donation link. Did I miss it?

**Comment by wpexplorer** [comment]
I would like to donate, any chance you will be setting up a paypal at some point? ;)

**Comment by sachinchoolur** [comment]
Hi @wpexplorer,
Sorry for the delayed response. I was on vacation.
I have an account on paypal  sachi77n@gmail.com is my email

Thanks
