### ISSUE TITLE
Lightslider doesn't refresh it's height on window resize

### ISSUE THREAD

**Issue by norin89** [sachinchoolur/lightslider#61]
First of all, I really appreciate you plugin and I always willingly us it!

To the point:
`.lightSlider` element doesn't refresh it's height on windows resize. I work on responsive websites and I small sliding gallery with couple of images inside. Those imgs are set to 100% width so heigh is fluid. Items count is set to 1 and on window resize width scales well but not height. If I resize down gallery get out of it's parent, resizing up bottom padding appear under the gallery.

Unfortunately I can't attach any screenshoot as the project is not public yet.

I tried to fire `slider.refresh();` on window refresh with no result.

Here's snippet of the code I use to bypass that issue:

``` javascript
var $gallery = $('#gallery'),
    slider = $gallery.children('.slides').lightSlider({
    item: 1,
    useCSS: false,
    mode:"slide"
    // ...
});
$(window).resize(function() {
    $lightSlider = $gallery.find('.lightSlider');
    $lightSlider.css('height', $lightSlider.find('.lslide').first().outerHeight(true));
});
```
## Update:

Setting `adaptiveHeight: true` did the job.

**Comment by Dakshank** [comment]
Having an issue when mobile chrome browser gets resize on the scroll.
You can check video recording for the same.
https://youtu.be/S-VYVmRJ5U8
