### ISSUE TITLE
Problem with vertical images and horizontal images in vertical mode

### ISSUE THREAD

**Issue by elodie-nazaret** [sachinchoolur/lightslider#76]
Hello,

I have a problem when I render the lightSlider in vertical mode : 
If I fix the minimum height (`adaptiveHeight`) : 

![fixedheightverticalmode](https://cloud.githubusercontent.com/assets/8955251/5540228/2b618972-8aca-11e4-8a94-0338558e1a93.png)

And If I don't fix the minimum height or if I fix a height greater than the height of all images: 

![noheightverticalmode](https://cloud.githubusercontent.com/assets/8955251/5540234/43b6ac5a-8aca-11e4-9f3e-6b563cd29c86.png)

I tried with `adaptiveHeight` but It seems not working while vertical mode is activated.

This is my JS code : 
``` javascript
var slider = $('.yllyImageSelectorContent').lightSlider({
            gallery:true,
            item: 1,
            auto: true,
            speed: 1000,
            vertical:true,
            verticalHeight:153,
            loop: true,
            vThumbWidth:50,
            thumbItem:5,
            thumbMargin:1,
            slideMargin:0
});
```

Thanks

**Comment by tristanbes** [comment]
:up: We're having the same problem. Is this going to be addressed ?

**Comment by sachinchoolur** [comment]
Hi @tristanbes,
I had already replied to @elodie-nazaret via email.
Currently lightslider does not support adaptiveHeight in vertical mode. you have to use fixed height.
I will inform you if i include this in future.

**Comment by tristanbes** [comment]
Okay thanks :-)
