### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by msurguy** [sachinchoolur/lightslider#78]
It seems there is no automated build process that this plugin uses. I suggest setting up a Gulp or Grunt file that will do the following:

- minify the assets when a new version gets released
- update the demo

Also somehow you would need to update bower repo and update npm repo for the plugin when a new version is released

Please check out this article on how to create a gulpfile:
http://www.smashingmagazine.com/2014/06/11/building-with-gulp/

**Comment by sachinchoolur** [comment]
Thanks :+1: 
Which one do you prefer Gulp or Grunt?

**Comment by msurguy** [comment]
@sachinchoolur Gulp is better to go forward in my opinion!

**Comment by sachinchoolur** [comment]
Hi,
I updated lightslider with yeoman jQuery generator..

Thanks
