### ISSUE TITLE
Video (YouTube, Vimeo) masking feature?

### ISSUE THREAD

**Issue by mikehdt** [sachinchoolur/lightslider#84]
This is a feature request. Having come to Lightslider from Owl Carousel (which seems to have sadly frozen for the time being), one excellent feature that it has that would be wonderful to see in Lightslider - perhaps as an optional plugin? - is the ability to "mask" videos from YouTube or Vimeo, making them tap-to-activate. The iframe is then destroyed when you slide across to another frame, to prevent a non-visible video from continuing to play audio.

The reason this would be great to have, is that if you have an embedded video then on a touch-input device such as a phone or tablet, an iframe cannot be swiped past - it effectively acts as a "touch sink". Although it becomes a touch sink anyway once you activate it, until then it at least keeps the slider "lightweight", by letting the user continue to swipe it normally and also by only having iframes exist when they are active. In the past, I've had to work on a site where a client could add a "video gallery" of YT videos, and having the slider feel quick and responsive was important.

The code in Owl Carousel's repository is very readable, but also very much tied in to the way Owl works, and the properties which are used internally. Maybe it has some ideas, as a starting point. I don't know how difficult this kind of functionality would be to implement within Lightslider, but what do you think?

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response.
You could try something like this http://jsfiddle.net/sachin377/2patspw2/309/.
When user click on any of these images the corresponding video iframe will be injected and that will be removed on  `onAfterSlide` funcion.

**Note:** I used dummy images as video placeholder
