### ISSUE TITLE
Responsive layout not working 

### ISSUE THREAD

**Issue by longteng429** [sachinchoolur/lightslider#88]
Hi, 

Thanks for your great slider plugin, I tried your lightslider. it is working great.

But the responsive code is not working on my case. Below is my code:
![2015-01-16 2 50 03](https://cloud.githubusercontent.com/assets/10556470/5771344/fe776df0-9d8e-11e4-9941-29e88bf8f10c.png)

jQuery(document).ready(function() {
	    var sliders =  jQuery("#lightSlider").lightSlider({
	    	 gallery:true,
	         item:1,
	         thumbItem:5,
	         loop:false,
	         responsive:[
	                       {
	                           breakpoint:800,
	                           settings: {
	                               item:1,
	                               thumbItem:3,
	                               slideMove:1,
	                               slideMargin:6,
	                             }
	                       },
	                       {
	                           breakpoint:480,
	                           settings: {
	                               item:1,
	                               thumbItem:2,
	                               slideMove:1
	                             }
	                       }
	                   ]            	        	    
	     });  
});

Is there any problem with my code cause the responsive not working ?

Thanks

**Comment by longteng429** [comment]
anyone can help ?

**Comment by sachinchoolur** [comment]
Hi
I am on vacation now. I will check this once i reach home

**Comment by sachinchoolur** [comment]
Hi,
Make sure that you did not set any fixed width for the container. If not please provide your website url if it is available .
