### ISSUE TITLE
how to create easy cross links (bottons or links) to specific slide?

### ISSUE THREAD

**Issue by mattrx86** [sachinchoolur/lightslider#89]
Hi,
i'm trying to connect external links or bottons to specific slide but i can't. Is there a way? I tried with working on Public proprieties but no way :(

**Comment by WaseemBepari** [comment]
use public method ***goToSlide()*** and specify the number to slide to the particular image
example is : http://jsfiddle.net/4ehzLpes/1/

**Comment by mattrx86** [comment]
Thank you, it works! I'm a noob, sorry.

**Comment by sachinchoolur** [comment]
Hi,
You can try this method http://jsfiddle.net/sachin377/4ehzLpes/5/
