### ISSUE TITLE
Vertically positioned controls for vertical mode

### ISSUE THREAD

**Issue by vmm86** [sachinchoolur/lightslider#90]
Hello!

Thanks for another good responsive image slider.

I believe that it would be much more reasonable to align controls vertically for vertical mode, like this:

```
___________________________
|            /\            |
|                          |
|                          |
|____________\/____________|
```

I mean that the axis of images' rotation (horizontal or vertical) should correlate with axis of controls' orientation.

Hope it will make sense. Good luck! ;-)

**Comment by sachinchoolur** [comment]
Hi,
I have updated this. Please check.
Thanks :+1:
