### ISSUE TITLE
Slider is not responsive

### ISSUE THREAD

**Issue by designil** [sachinchoolur/lightslider#92]
Hello,

Thank you for developing this awesome slider! :) I really love how simple it is to setup.

I used the same code from Codepen demo:
http://codepen.io/sachinchoolur/pen/Ihoev

However, my slider is not responsive for some reasons.
Please see the working site here: http://goo.gl/LhTSiV

Screenshot:
![Screenshot](http://i.imgur.com/h1ClY3I.png)

Please let me know if there is anything wrong with the code.

Best Regards,
Woratana

**Comment by sachinchoolur** [comment]
Hi,
There are so many javascript  errors on your page (creamsoda_ticker.js). I think because of these errors lightslider is not working properly.

**Comment by g-ilham** [comment]
@sachinchoolur 
I have the same problem.
Here is my code.
html to take out of your demo:
```
ul#lightSlider.gallery
  li.clone.left data-thumb="http://sachinchoolur.github.io/img/thumb/cS-15.jpg"
    a href="#"
      img src="http://sachinchoolur.github.io/img/cS-15.jpg" /
  li.lslide data-thumb="http://sachinchoolur.github.io/img/thumb/cS-1.jpg"
    a href="#"
      img src="http://sachinchoolur.github.io/img/cS-1.jpg" /
  li.lslide data-thumb="http://sachinchoolur.github.io/img/thumb/cS-2.jpg"
    a href="#"
      img src="http://sachinchoolur.github.io/img/cS-2.jpg" /
  li.lslide data-thumb="http://sachinchoolur.github.io/img/thumb/cS-3.jpg"
    a href="#"
      img src="http://sachinchoolur.github.io/img/cS-3.jpg" /
```

And js code too:
```
    $('#lightSlider').lightSlider({
      gallery:true,
      item:1,
      autoWidth: true,
      thumbItem:9,
      slideMargin: 0
    });
```

What happens at the output: 
![alt text](http://cs623931.vk.me/v623931375/21c47/BXV2ICKRKOE.jpg "Gallery")

**Comment by g-ilham** [comment]
Guys apologize for their incompetence. Found the answer: it was necessary to add these styles:
```
ul.gallery {
    list-style: none outside none;
    padding-left: 0;
    margin-bottom:0;
    li.gallery-li {
        display: block;
        float: left;
        margin-right: 6px;
        cursor:pointer;
        img.gallery-img {
            display: block;
            height: auto;
            max-width: 100%;
        }

    }
}

```
Once again I apologize for my stupidity.
I think, can close this issue.
 Thank U.
