### ISSUE TITLE
videos with lightgallery integration

### ISSUE THREAD

**Issue by matthiaswagnerwy** [sachinchoolur/lightslider#95]
hy,

i am trying to integrate lightgallery for a fullscreen version of the slider-contents. so far that is no problem with the documentation.
but it get's tricky when there are videos in the slider, as they fail with the data-src attribute.

an easy solution would be to use the masking feature you explained in issue #84. so i could use preview-images for the videos in the slider as well as in fullscreen-mode, and then just append the iframe on click.

the only problem with that is that i can't know which slides hold videos in gallery-mode, after it gets fired from slider with
onSliderLoad: function (el) {
 el.lightGallery();
}
as all the attributes from the slider-elements get lost.

is there a way to keep a "data-iframe" attribute for a list-element from lightSlider when firing the fullscreen mode with lightGallery?

thanks,
matt

**Comment by sachinchoolur** [comment]
Hi Matt,
With current functionality this is not possible. I have created a jsfiddle demo with updated lightGallery.js 
http://jsfiddle.net/sachin377/p1aw7utk/11/
`data-iframe` attribute will be taken from lightslider list and appended to lightGallery li.

**Comment by matthiaswagnerwy** [comment]
great, i will give it a try :)
