### ISSUE TITLE
Alternative transition effects possible

### ISSUE THREAD

**Issue by nickbe** [sachinchoolur/lightslider#96]
How difficult would it be to integrate additional transition effects?
Example: http://demo.getgrav.org/deliver-skeleton

Cheers
Nick

**Comment by sachinchoolur** [comment]
Hi,
I have been really busy lately so i couldn't replay you on time. I am really sorry for that.
With default functionality this is not possible. But i think if you use callbacks wisely for adding/ removing custom class you can achieve this. I will try to add a demo on website if i get some free time.
