### ISSUE TITLE
Height issue on refresh

### ISSUE THREAD

**Issue by vajkri** [sachinchoolur/lightslider#98]
I can't get the slider to recalculate the height of slides on refresh. I am running the refresh on window resize, but it doesn't seem to do anything.

```javascript
if($sliderDiv.length) {
    var $slider = $sliderDiv.lightSlider({
        item: 1
    });
}

$(window).on('resize', function() {
    $slider.refresh();
});
```

Should i be doing something differently? Thanks in advance.

**Comment by norin89** [comment]
Add `adaptiveHeight` parameter set to `true`. Then you don't need to refresh the slider on window resize.

**Comment by vajkri** [comment]
Ok that did it, thanks! :+1:
