### ISSUE TITLE
Hide controls on end

### ISSUE THREAD

**Issue by scazzy** [sachinchoolur/lightslider#99]
Arrow controls should hide on reaching a specific end.
Or class should be added, and a callback. based on which css can be applied.

**Comment by ocvninfo** [comment]
https://github.com/ocvninfo/lightslider/commit/9c8f2b216f7822c17eb877fa8af6a317cf4026a4

**Comment by christopheschwyzer** [comment]
:+1:

**Comment by ozij** [comment]
Good

**Comment by tobias47n9e** [comment]
Has this been merged yet and what version will include the fix?

**Comment by LincolnLex44** [comment]
Any news on merging this in? Would be great functionality no doubt.

**Comment by LincolnLex44** [comment]
I'm gonna take it that lightslider development is dead and look for a different package.
